# Sync tests: R channel registry (R/sysdata.rda, generated by
# data-raw/build_channels.R) vs Rust constants
# (src/rust/catalog/src/channels.rs).
#
# The two artifacts are generated from the same single source of truth and
# must stay bit-identical (canonical order, docs/research/04 section 1 and
# docs/research/05 section 2). Any mismatch fails the suite (D5: channel
# validation is by label, zero magic strings).

.ms_channel_tables <- function() {
  # sysdata.rda is lazily loaded into the namespace at install time (the file
  # itself is not shipped), so read the object through the namespace: this
  # works under devtools::load_all(), library() and R CMD check alike.
  get("channel_tables", envir = asNamespace("msuiter"))
}

.ms_rust_channel_constants <- function() {
  path <- testthat::test_path("../../src/rust/catalog/src/channels.rs")
  if (!file.exists(path)) {
    # The sync guard compares the R registry with the Rust source constants:
    # it is a repository-drift test, not an installed-package property, so it
    # skips when the Rust source tree is absent (R CMD check of a tarball).
    skip("Rust source tree not available (R CMD check context)")
  }
  text <- paste(readLines(path, warn = FALSE), collapse = "\n")
  pattern <- paste0(
    "(?s)pub (?:const|static)\\s+([A-Z0-9_]+)_CHANNELS\\s*:\\s*\\[&str;\\s*([0-9]+)\\]",
    "\\s*=\\s*\\[(.*?)\\];"
  )
  m <- gregexec(pattern, text, perl = TRUE)
  matches <- regmatches(text, m)[[1]]
  # gregexec rows = capture groups (full match + 3 groups); columns = the 5
  # channel tables found in channels.rs.
  stopifnot(identical(nrow(matches), 4L), ncol(matches) == 5L)
  out <- list()
  for (i in seq_len(ncol(matches))) {
    name <- matches[2L, i]
    declared_n <- as.integer(matches[3L, i])
    body <- matches[4L, i]
    entries <- strsplit(body, ",", fixed = TRUE)[[1]]
    entries <- trimws(gsub("\"", "", entries, fixed = TRUE))
    entries <- entries[nzchar(entries)]
    stopifnot(length(entries) == declared_n)
    out[[name]] <- entries
  }
  out
}

test_that("channel registry ships the five canonical tables", {
  tables <- .ms_channel_tables()
  expect_setequal(
    names(tables),
    c("SBS96", "SBS192", "SBS384", "SBS1536", "DBS78")
  )
  expect_identical(
    vapply(tables, function(x) length(x$labels), integer(1)),
    c(SBS96 = 96L, SBS192 = 192L, SBS384 = 384L, SBS1536 = 1536L, DBS78 = 78L)
  )
  for (nm in names(tables)) {
    tbl <- tables[[nm]]
    expect_true(is.character(tbl$labels), info = nm)
    expect_false(anyNA(tbl$labels), info = nm)
    expect_true(all(nzchar(tbl$labels)), info = nm)
    expect_identical(anyDuplicated(tbl$labels), 0L, info = nm)
    expect_match(tbl$labels, tbl$pattern, all = TRUE, info = nm)
    expect_true(is.data.frame(tbl$decomposition), info = nm)
    expect_identical(nrow(tbl$decomposition), length(tbl$labels), info = nm)
  }
})

test_that("Rust channel constants match R labels bit for bit", {
  tables <- .ms_channel_tables()
  rust <- .ms_rust_channel_constants()
  expect_setequal(
    names(rust),
    c("SBS96", "SBS192", "SBS384", "SBS1536", "DBS78")
  )
  for (nm in names(tables)) {
    expect_identical(rust[[nm]], tables[[nm]]$labels, info = nm)
  }
})
