# FFI surface drift guard (U-M0-09; docs/ffi-surface.md).
#
# Repository-drift semantics (same pattern as test-channels-sync.R): the
# guard compares the machine-readable export manifest inside
# docs/ffi-surface.md with the exports actually generated by rextendr
# (R/extendr-wrappers.R). Any drift — a new, removed or renamed
# msffi_*/ms_*_rust export that did not go through the frozen-surface
# review — turns this test red. Skips under R CMD check of a tarball,
# where the docs/ and generated-wrapper sources are absent.

.ms_ffi_surface_manifest <- function() {
  path <- testthat::test_path("../../docs/ffi-surface.md")
  if (!file.exists(path)) {
    skip("docs/ffi-surface.md not available (R CMD check context)")
  }
  text <- paste(readLines(path, warn = FALSE), collapse = "\n")
  m <- regexpr(
    "(?s)```msuiter-ffi-surface\\s*\n(.*?)\n```",
    text,
    perl = TRUE
  )
  if (m < 0L) {
    stop("docs/ffi-surface.md: missing ```msuiter-ffi-surface manifest block")
  }
  cs <- attr(m, "capture.start")[1L]
  cl <- attr(m, "capture.length")[1L]
  block <- substr(text, cs, cs + cl - 1L)
  names <- trimws(strsplit(block, "\n", fixed = TRUE)[[1]])
  names[nzchar(names)]
}

.ms_ffi_surface_actual_exports <- function() {
  path <- testthat::test_path("../../R/extendr-wrappers.R")
  if (!file.exists(path)) {
    skip("R/extendr-wrappers.R not available (R CMD check context)")
  }
  text <- paste(readLines(path, warn = FALSE), collapse = "\n")
  # Generated passthroughs call .Call(wrap__<name>, ...); the wrap__ prefix
  # marks every registered Rust export.
  all <- regmatches(text, gregexpr("wrap__[A-Za-z0-9_]+", text, perl = TRUE))[[1]]
  unique(sub("^wrap__", "", all))
}

test_that("ffi-surface.md manifest matches the generated Rust exports", {
  documented <- .ms_ffi_surface_manifest()
  actual <- .ms_ffi_surface_actual_exports()

  expect_true(length(documented) > 0L)
  expect_false(anyDuplicated(documented) > 0L)
  # The frozen contract: no export outside the reviewed surface, none missing.
  expect_setequal(actual, documented)
})
