# Structural tests for the channel registry (R/sysdata.rda, generated by
# data-raw/build_channels.R).
#
# These encode the canonical-order contract audited in docs/research/04
# section 1 (SigProfilerMatrixGenerator semantics: master SBS index, tsb /
# bias_sort strand order, DBS pyrimidine-start normalization and Q-type
# folding) and docs/research/05 section 2 (canonical label lists, SBS96
# flank-major order, SBS192 = 96 x {T,U}). The rule for all three
# non-stranded tables is: canonical order == ASCII lexicographic order of
# the label (A < C < G < T); stranded tables prepend T/U/B/N blocks in SPMG
# bias_sort order with the SBS96 order inside each block.

.ms_channel_tables <- function() {
  # sysdata.rda is lazily loaded into the namespace at install time (the file
  # itself is not shipped), so read the object through the namespace: this
  # works under devtools::load_all(), library() and R CMD check alike.
  get("channel_tables", envir = asNamespace("msuiter"))
}

tables <- .ms_channel_tables()

test_that("SBS96 is flank-major lexicographic with canonical class blocks", {
  lbl <- tables$SBS96$labels
  expect_identical(lbl, sort(lbl))
  expect_identical(lbl[[1]], "A[C>A]A")
  expect_identical(lbl[[length(lbl)]], "T[T>G]T")
  dec <- tables$SBS96$decomposition
  # flank5 is the outermost dimension (blocks of 24), then the 6 substitution
  # classes in COSMIC order (blocks of 4), then flank3 (innermost).
  expect_identical(
    unique(dec$flank5), c("A", "C", "G", "T")
  )
  expect_identical(
    unique(paste(dec$ref, dec$alt, sep = ">")),
    c("C>A", "C>G", "C>T", "T>A", "T>C", "T>G")
  )
  expect_true(all(dec$ref %in% c("C", "T"))) # pyrimidine-centered
  expect_identical(unique(dec$flank3), c("A", "C", "G", "T"))
})

test_that("SBS192 / SBS384 are TSB blocks over SBS96 in SPMG bias_sort order", {
  sbs96 <- tables$SBS96$labels
  for (nm in c("SBS192", "SBS384")) {
    tbl <- tables[[nm]]
    strands <- substr(tbl$labels, 1L, 1L)
    expect_identical(
      unique(strands),
      switch(nm, SBS192 = c("T", "U"), SBS384 = c("T", "U", "B", "N")),
      info = nm
    )
    # Each contiguous strand block holds exactly the SBS96 labels, in order.
    for (s in unique(strands)) {
      block <- tbl$labels[strands == s]
      block <- block[seq_along(sbs96)] # keep block-local ordering
      expect_identical(substr(block, 3L, nchar(block)), sbs96, info = nm)
    }
    # Strand state semantics follow SPMG's transcription encoding.
    expect_identical(
      unique(tbl$decomposition$strand_state),
      unname(c(T = "transcribed", U = "untranscribed",
               B = "bidirectional", N = "non-transcribed")[unique(strands)]),
      info = nm
    )
  }
  expect_identical(tables$SBS192$labels[[1]], "T:A[C>A]A")
  expect_identical(tables$SBS192$labels[[192]], "U:T[T>G]T")
  expect_identical(tables$SBS384$labels[[1]], "T:A[C>A]A")
  expect_identical(tables$SBS384$labels[[384]], "N:T[T>G]T")
})

test_that("SBS1536 is pentanucleotide lexicographic projecting onto SBS96", {
  lbl <- tables$SBS1536$labels
  expect_identical(lbl, sort(lbl))
  expect_identical(lbl[[1]], "AA[C>A]AA")
  expect_identical(lbl[[length(lbl)]], "TT[T>G]TT")
  # Dropping the outermost bases of every pentanucleotide label recovers the
  # SBS96 label set exactly (lossless coarse-graining, fine -> coarse).
  projection <- unique(substr(lbl, 2L, 8L))
  expect_identical(sort(projection), sort(tables$SBS96$labels))
})

test_that("DBS78 refs/alts follow SPMG normalization and cover all doublets", {
  lbl <- tables$DBS78$labels
  expect_identical(lbl, sort(lbl))
  expect_identical(lbl[[1]], "AC>CA")
  expect_identical(lbl[[length(lbl)]], "TT>GG")
  dec <- tables$DBS78$decomposition
  # Canonical ref groups (pyrimidine-start 4 + mixed 2 + self-revcomp 4).
  expect_setequal(
    unique(dec$ref),
    c("AC", "AT", "CC", "CG", "CT", "GC", "TA", "TC", "TG", "TT")
  )
  # Group sizes: 9 alts for revcompl-asymmetric refs, 6 for the
  # self-reverse-complement (Q-type) refs after alt folding.
  sizes <- table(dec$ref)
  expect_identical(
    as.integer(sizes[c("AC", "AT", "CC", "CG", "CT", "GC", "TA", "TC", "TG", "TT")]),
    c(9L, 6L, 9L, 6L, 9L, 6L, 6L, 9L, 9L, 9L)
  )
  # Both positions of every channel change (no single-base events).
  expect_true(all(substr(dec$alt, 1, 1) != substr(dec$ref, 1, 1)))
  expect_true(all(substr(dec$alt, 2, 2) != substr(dec$ref, 2, 2)))

  # Coverage contract: over the 144 doublet mutations where both positions
  # change, exactly one of each reverse-complement pair is a channel.
  comp <- c(A = "T", C = "G", G = "C", T = "A")
  revcompl <- function(d) paste0(comp[substr(d, 2, 2)], comp[substr(d, 1, 1)])
  refs <- expand.grid(y = c("A", "C", "G", "T"), x = c("A", "C", "G", "T"),
                      stringsAsFactors = FALSE)
  refs$ref <- paste0(refs$x, refs$y)
  alts <- expand.grid(z = c("A", "C", "G", "T"), n = c("A", "C", "G", "T"),
                      stringsAsFactors = FALSE)
  alts$alt <- paste0(alts$n, alts$z)
  grid <- merge(refs["ref"], alts["alt"], by = NULL)
  grid <- grid[substr(grid$alt, 1, 1) != substr(grid$ref, 1, 1) &
                 substr(grid$alt, 2, 2) != substr(grid$ref, 2, 2), ]
  muts <- paste0(grid$ref, ">", grid$alt)
  expect_identical(length(muts), 144L)
  hit <- muts %in% lbl
  mirror <- paste0(revcompl(grid$ref), ">", revcompl(grid$alt)) %in% lbl
  selfeq <- muts == paste0(revcompl(grid$ref), ">", revcompl(grid$alt))
  expect_true(all(hit[selfeq])) # self-revcompl mutations are their own channel
  expect_true(all(xor(hit[!selfeq], mirror[!selfeq])))
})
