//! SBS channel arithmetic: SBS96 / SBS192 / SBS384 / SBS1536 (U-M1s-06).
//!
//! Semantic source of truth: SigProfilerMatrixGenerator (SPMG), audited at
//! `docs/research/04` section 1 and re-verified line-by-line against the
//! upstream source (`SigProfilerMatrixGenerator/scripts/`):
//!   * five-base +/-2 window and REF-vs-genome skip
//!     (`MutationMatrixGenerator.py:778-808`);
//!   * pyrimidine orientation: REF in {A,G} => `revbias` on the strand bias
//!     (T<->U, B/N unchanged), complement REF/ALT, reverse-complement the
//!     window (`:833-837`, helpers `:420-445`);
//!   * channel key `bias:XY[R>M]ZW` (`:907-917`);
//!   * strand encoding `tsb_ref` (0-3 non-genic ACGT => bias "N", 4-7 "T",
//!     8-11 "U", 12-15 "B", 16-19 literal N) and `bias_sort`
//!     {T:0, U:1, B:2, N:3} (`SigProfilerMatrixGeneratorFunc.py:173-199`);
//!   * the 6144 index enumerates pyrimidine-centered **ACGT** 5-mers only
//!     (`SigProfilerMatrixGeneratorFunc.py:1004-1034`), and the 96/384/1536
//!     matrices are string slices of those keys
//!     (`MutationMatrixGenerator.py:2990-3013`).
//!
//! The canonical label ORDER is owned by `channels.rs` (generated by
//! `data-raw/build_channels.R` and pinned to `R/sysdata.rda`); the functions
//! here are the byte arithmetic that addresses those tables. Index layout:
//!
//! ```text
//! idx96   = f5*24 + class*4 + f3
//! idx1536 = (f5a*4 + f5b)*96 + class*16 + (f3a*4 + f3b)
//! idx192  = strand_block(T=0, U=1)      * 96 + idx96
//! idx384  = strand_block(T=0, U=1, B=2, N=3) * 96 + idx96
//! ```
//! with base4 = {A:0, C:1, G:2, T:3} and class = {C>A:0, C>G:1, C>T:2,
//! T>A:3, T>C:4, T>G:5} (both ASCII-lexicographic, matching the tables).
//!
//! # Design (per IMPLEMENTATION-PLAN U-M1s-06)
//!
//! Context is supplied by the caller as bytes; this module is a pure,
//! allocation-free (hot path) arithmetic layer with no genome I/O. Fetching
//! the +/-1 / +/-2 window from a reference genome, checking REF against it,
//! and routing skip-worthy mutations is the assembly layer's job
//! (U-M1s-07/08). The ref allele is the center byte of the context, so the
//! SPMG "context middle != REF" failure mode is structurally impossible
//! here.
//!
//! # Ambiguity policy (documented per the SPMG contract)
//!
//! * **N or any non-ACGT byte in the window**: structured
//!   [`MsError`](msuiter_engine::MsError) with topic `"argument"` and the
//!   1-based window position in `i`. Rationale: SPMG's 6144 index contains
//!   no N-context key, so such a mutation hits an uncaught KeyError there
//!   (a hard crash, *not* a logged skip — only the DBS path has an N-guard);
//!   msuiter's structured error is a deliberate hardening, and the assembly
//!   layer routes it to the same skip ledger. Note the window this
//!   module sees: for exact SPMG parity of the 96-family the caller must
//!   consult the +/-2 window (an N at +/-2 is invisible to a trinucleotide
//!   input yet still drops the mutation from every SPMG SBS matrix).
//! * **SBS192 with [`Strand::Bidirectional`] / [`Strand::None`]**:
//!   structured error. SBS192 is a msuiter table (SPMG itself folds only
//!   96/384/1536 out of 6144); it carries T/U blocks only, so B/N-biased
//!   mutations have no channel there and must be skipped for that matrix
//!   (counted in the B/N blocks of SBS384 instead).
//! * **Slice variants** validate the window length (3 for the 96-family, 5
//!   for SBS1536) and report the observed length in `i`; the fixed-size
//!   array API makes a wrong length unrepresentable at compile time.
//!
//! Error `i` conventions (1-based, R style): context-base errors carry the
//! offending window position (1 = outermost 5' base; the ref/alt center is
//! position 2 for the +/-1 window and 3 for the +/-2 window); ref==alt and
//! invalid-alt errors carry that same center position; bounds errors on
//! [`channel_label`] carry `i` = 1-based channel index and `j` = table
//! length.

use msuiter_engine::MsError;

use crate::channels::{SBS1536_CHANNELS, SBS192_CHANNELS, SBS384_CHANNELS, SBS96_CHANNELS};

/// SPMG transcription-strand bias category of a variant.
///
/// Mirrors the four bias labels of SPMG's pre-encoded genome (`tsb_ref`,
/// `SigProfilerMatrixGeneratorFunc.py:173-197`): transcribed /
/// untranscribed / bidirectional promoter / no annotation (non-genic ACGT
/// or literal N reference).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Strand {
    /// Bias "T": transcribed strand.
    Transcribed,
    /// Bias "U": untranscribed strand.
    Untranscribed,
    /// Bias "B": bidirectional promoter.
    Bidirectional,
    /// Bias "N": no strand annotation (non-genic ACGT or N reference).
    None,
}

impl Strand {
    /// The bias category after SPMG re-orientation: `revbias` swaps T<->U
    /// and fixes B and N (`MutationMatrixGenerator.py:435-445`).
    #[inline]
    pub fn flipped(self) -> Self {
        match self {
            Strand::Transcribed => Strand::Untranscribed,
            Strand::Untranscribed => Strand::Transcribed,
            Strand::Bidirectional | Strand::None => self,
        }
    }

    /// The SPMG bias label: `"T"`, `"U"`, `"B"` or `"N"`.
    #[inline]
    pub fn bias_label(self) -> &'static str {
        match self {
            Strand::Transcribed => "T",
            Strand::Untranscribed => "U",
            Strand::Bidirectional => "B",
            Strand::None => "N",
        }
    }

    /// Block offset (in 96-channel units) within the SBS192 T/U table;
    /// `None` for B/N, which have no SBS192 channel (bias_sort order).
    #[inline]
    fn block_192(self) -> Option<usize> {
        match self {
            Strand::Transcribed => Some(0),
            Strand::Untranscribed => Some(1),
            Strand::Bidirectional | Strand::None => None,
        }
    }

    /// Block offset within the SBS384 T/U/B/N table (bias_sort order).
    #[inline]
    fn block_384(self) -> Option<usize> {
        match self {
            Strand::Transcribed => Some(0),
            Strand::Untranscribed => Some(1),
            Strand::Bidirectional => Some(2),
            Strand::None => Some(3),
        }
    }
}

/// base4 code of an allele byte: A:0, C:1, G:2, T:3.
#[inline]
fn base4(b: u8) -> Option<usize> {
    match b {
        b'A' => Some(0),
        b'C' => Some(1),
        b'G' => Some(2),
        b'T' => Some(3),
        _ => None,
    }
}

/// Substitution-class index for an oriented (pyrimidine-centered) variant:
/// C>A:0, C>G:1, C>T:2, T>A:3, T>C:4, T>G:5 (ASCII order of the `[C>A]`
/// class labels). `center` is the base4 code of the oriented ref (1 = C,
/// 3 = T); `alt` is the base4 code of the oriented alt.
#[inline]
const fn sub_class(center: usize, alt: usize) -> Option<usize> {
    match (center, alt) {
        (1, 0) => Some(0), // C>A
        (1, 2) => Some(1), // C>G
        (1, 3) => Some(2), // C>T
        (3, 0) => Some(3), // T>A
        (3, 1) => Some(4), // T>C
        (3, 2) => Some(5), // T>G
        _ => None,
    }
}

/// `argument` error for a non-ACGT byte at 1-based window position `pos`.
fn bad_base(byte: u8, pos: usize, width: usize) -> MsError {
    MsError::new(
        "argument",
        format!(
            "invalid allele byte 0x{byte:02X} at 1-based context position {pos}/{width} (expected A, C, G or T)"
        ),
    )
    .with_i(pos as i64)
}

/// `argument` error for a wrong window length.
fn bad_context_len(observed: usize, expected: usize) -> MsError {
    MsError::new(
        "argument",
        format!("context window must be exactly {expected} bytes, got {observed}"),
    )
    .with_i(observed as i64)
}

/// `argument` error for ref == alt at the center slot.
fn ref_equal_alt(center_pos: usize) -> MsError {
    MsError::new(
        "argument",
        "ref and alt alleles are identical; not a substitution",
    )
    .with_i(center_pos as i64)
}

/// Validate a +/-1 window and orient it to the pyrimidine strand.
///
/// Returns `(f5, class, f3, flipped)`: base4 codes of the oriented flanks,
/// the substitution class of the oriented variant, and whether SPMG
/// re-orientation happened (purine center => `revcompl` + `revbias`). SPMG
/// semantics (`MutationMatrixGenerator.py:815-824`): a purine center (A/G)
/// complements to its pyrimidine, the flanks swap as the reverse
/// complement, and the alt complements; code arithmetic is
/// `complement(code) = 3 - code`.
#[inline]
fn orient_trinucleotide(ctx: &[u8; 3], alt: u8) -> Result<(usize, usize, usize, bool), MsError> {
    let l = base4(ctx[0]).ok_or_else(|| bad_base(ctx[0], 1, 3))?;
    let m = base4(ctx[1]).ok_or_else(|| bad_base(ctx[1], 2, 3))?;
    let r = base4(ctx[2]).ok_or_else(|| bad_base(ctx[2], 3, 3))?;
    let a = base4(alt).ok_or_else(|| bad_base(alt, 2, 3))?;
    if a == m {
        return Err(ref_equal_alt(2));
    }
    // Purine centers are base4 codes 0 (A) and 2 (G).
    if m == 0 || m == 2 {
        let class = sub_class(3 - m, 3 - a)
            .ok_or_else(|| MsError::new("argument", "oriented center is not a pyrimidine (internal)"))?;
        Ok((3 - r, class, 3 - l, true))
    } else {
        let class = sub_class(m, a)
            .ok_or_else(|| MsError::new("argument", "oriented center is not a pyrimidine (internal)"))?;
        Ok((l, class, r, false))
    }
}

/// Validate a +/-2 window and orient it to the pyrimidine strand.
///
/// Returns `(f5, class, f3)`: the two-flank codes (0..16, ASCII order =
/// `f5a*4 + f5b`) around the oriented center, and the substitution class.
/// A purine center reverse-complements the whole five-base window (SPMG
/// `revcompl`, applied to the 5-mer as one string).
#[inline]
fn orient_pentanucleotide(ctx: &[u8; 5], alt: u8) -> Result<(usize, usize, usize), MsError> {
    let mut c = [0usize; 5];
    for (k, &byte) in ctx.iter().enumerate() {
        c[k] = base4(byte).ok_or_else(|| bad_base(byte, k + 1, 5))?;
    }
    let a = base4(alt).ok_or_else(|| bad_base(alt, 3, 5))?;
    if a == c[2] {
        return Err(ref_equal_alt(3));
    }
    if c[2] == 0 || c[2] == 2 {
        let class = sub_class(3 - c[2], 3 - a)
            .ok_or_else(|| MsError::new("argument", "oriented center is not a pyrimidine (internal)"))?;
        Ok((
            (3 - c[4]) * 4 + (3 - c[3]),
            class,
            (3 - c[1]) * 4 + (3 - c[0]),
        ))
    } else {
        let class = sub_class(c[2], a)
            .ok_or_else(|| MsError::new("argument", "oriented center is not a pyrimidine (internal)"))?;
        Ok((c[0] * 4 + c[1], class, c[3] * 4 + c[4]))
    }
}

/// SBS96 channel index of a single-base substitution.
///
/// `ctx` is the +/-1 trinucleotide `[5' flank, ref, 3' flank]`; the ref
/// allele is its center byte. Pyrimidine-oriented (SPMG): purine-centered
/// inputs are complement-flipped before indexing, so both strands of the
/// same mutation land on one channel.
#[inline]
pub fn assign_sbs96(ctx: &[u8; 3], alt: u8) -> Result<usize, MsError> {
    let (f5, class, f3, _) = orient_trinucleotide(ctx, alt)?;
    Ok(f5 * 24 + class * 4 + f3)
}

/// SBS192 channel index: the SBS96 channel inside the transcribed (T) or
/// untranscribed (U) block, SPMG bias_sort order (T first, then U).
///
/// Orientation flips the block (SPMG `revbias`, `:819`): a purine-centered
/// variant annotated T lands in the U block of the oriented channel and
/// vice versa. [`Strand::Bidirectional`] and [`Strand::None`] have no
/// channel in this table (structured error; see the module-level ambiguity
/// policy).
#[inline]
pub fn assign_sbs192(ctx: &[u8; 3], alt: u8, strand: Strand) -> Result<usize, MsError> {
    let (f5, class, f3, flipped) = orient_trinucleotide(ctx, alt)?;
    let block = if flipped { strand.flipped() } else { strand }
        .block_192()
        .ok_or_else(|| {
            MsError::new(
                "argument",
                "strand bias B/N has no SBS192 channel (T/U table); skip for this matrix or use SBS384",
            )
        })?;
    Ok(block * 96 + f5 * 24 + class * 4 + f3)
}

/// SBS384 channel index: the SBS96 channel inside the T/U/B/N strand-bias
/// blocks, SPMG bias_sort order (T, U, B, N). Orientation flips T<->U and
/// leaves B and N blocks fixed (SPMG `revbias`).
#[inline]
pub fn assign_sbs384(ctx: &[u8; 3], alt: u8, strand: Strand) -> Result<usize, MsError> {
    let (f5, class, f3, flipped) = orient_trinucleotide(ctx, alt)?;
    let block = if flipped { strand.flipped() } else { strand }
        .block_384()
        .ok_or_else(|| {
            MsError::new("argument", "unreachable: block_384 covers all Strand variants (internal)")
        })?;
    Ok(block * 96 + f5 * 24 + class * 4 + f3)
}

/// SBS1536 channel index of a single-base substitution with its +/-2
/// pentanucleotide context `[5'2, ref, 3'2]` (ref is the center byte).
///
/// Same pyrimidine orientation as SBS96, applied to the full five-base
/// window (SPMG reverse-complements the whole 5-mer). The table projects
/// losslessly onto SBS96: the inner trinucleotide of any 1536 label is the
/// SBS96 label of the same variant.
#[inline]
pub fn assign_sbs1536(ctx: &[u8; 5], alt: u8) -> Result<usize, MsError> {
    let (f5, class, f3) = orient_pentanucleotide(ctx, alt)?;
    Ok(f5 * 96 + class * 16 + f3)
}

/// Slice-based SBS96 assignment; reports a wrong window length as a
/// structured `"argument"` error with the observed length in `i`.
#[inline]
pub fn assign_sbs96_slice(context: &[u8], alt: u8) -> Result<usize, MsError> {
    let ctx: &[u8; 3] = context
        .try_into()
        .map_err(|_| bad_context_len(context.len(), 3))?;
    assign_sbs96(ctx, alt)
}

/// Slice-based SBS192 assignment (window length 3).
#[inline]
pub fn assign_sbs192_slice(context: &[u8], alt: u8, strand: Strand) -> Result<usize, MsError> {
    let ctx: &[u8; 3] = context
        .try_into()
        .map_err(|_| bad_context_len(context.len(), 3))?;
    assign_sbs192(ctx, alt, strand)
}

/// Slice-based SBS384 assignment (window length 3).
#[inline]
pub fn assign_sbs384_slice(context: &[u8], alt: u8, strand: Strand) -> Result<usize, MsError> {
    let ctx: &[u8; 3] = context
        .try_into()
        .map_err(|_| bad_context_len(context.len(), 3))?;
    assign_sbs384(ctx, alt, strand)
}

/// Slice-based SBS1536 assignment (window length 5).
#[inline]
pub fn assign_sbs1536_slice(context: &[u8], alt: u8) -> Result<usize, MsError> {
    let ctx: &[u8; 5] = context
        .try_into()
        .map_err(|_| bad_context_len(context.len(), 5))?;
    assign_sbs1536(ctx, alt)
}

/// Canonical label of a channel index in a channel table.
///
/// Bounds-checked per FFI contract 4 (out-of-range is a structured
/// `"bounds"` error with `i` = 1-based index and `j` = table length, never
/// a panic).
pub fn channel_label<'a>(table: &[&'a str], idx: usize) -> Result<&'a str, MsError> {
    table.get(idx).copied().ok_or_else(|| {
        MsError::new(
            "bounds",
            format!("channel index {idx} outside table of {} channels", table.len()),
        )
        .with_i(idx as i64 + 1)
        .with_j(table.len() as i64)
    })
}

/// Label of an SBS96 channel in canonical order.
#[inline]
pub fn sbs96_label(idx: usize) -> Result<&'static str, MsError> {
    channel_label(&SBS96_CHANNELS, idx)
}

/// Label of an SBS192 channel in canonical order.
#[inline]
pub fn sbs192_label(idx: usize) -> Result<&'static str, MsError> {
    channel_label(&SBS192_CHANNELS, idx)
}

/// Label of an SBS384 channel in canonical order.
#[inline]
pub fn sbs384_label(idx: usize) -> Result<&'static str, MsError> {
    channel_label(&SBS384_CHANNELS, idx)
}

/// Label of an SBS1536 channel in canonical order.
#[inline]
pub fn sbs1536_label(idx: usize) -> Result<&'static str, MsError> {
    channel_label(&SBS1536_CHANNELS, idx)
}
