//! Channel registry integration tests (pure Rust, no FFI).
//!
//! The arrays in `src/channels.rs` are generated by `data-raw/build_channels.R`
//! and must stay bit-identical to `R/sysdata.rda` (`channel_tables`); that R/Rust
//! sync is enforced by `tests/testthat/test-channels-sync.R`. These tests pin the
//! structural contract of the generated constants themselves: canonical lengths
//! and anchor labels. Canonical-order provenance: `docs/research/04` section 1
//! (SPMG semantics) and `docs/research/05` section 2 (canonical label lists).

use std::collections::HashSet;

use msuiter_catalog::channels::{
    DBS78_CHANNELS, SBS1536_CHANNELS, SBS192_CHANNELS, SBS384_CHANNELS, SBS96_CHANNELS,
};

/// Canonical table sizes (SBS96 / SBS192 / SBS384 / SBS1536 / DBS78).
#[test]
fn canonical_lengths() {
    assert_eq!(SBS96_CHANNELS.len(), 96);
    assert_eq!(SBS192_CHANNELS.len(), 192);
    assert_eq!(SBS384_CHANNELS.len(), 384);
    assert_eq!(SBS1536_CHANNELS.len(), 1536);
    assert_eq!(DBS78_CHANNELS.len(), 78);
}

/// First/last label of every table in canonical order.
#[test]
fn anchor_labels() {
    assert_eq!(SBS96_CHANNELS[0], "A[C>A]A");
    assert_eq!(SBS96_CHANNELS[95], "T[T>G]T");

    // Stranded tables: T/U (SBS192) and T/U/B/N (SBS384) blocks in SPMG
    // bias_sort order, SBS96 order within each block.
    assert_eq!(SBS192_CHANNELS[0], "T:A[C>A]A");
    assert_eq!(SBS192_CHANNELS[95], "T:T[T>G]T");
    assert_eq!(SBS192_CHANNELS[96], "U:A[C>A]A");
    assert_eq!(SBS192_CHANNELS[191], "U:T[T>G]T");

    assert_eq!(SBS384_CHANNELS[0], "T:A[C>A]A");
    assert_eq!(SBS384_CHANNELS[95], "T:T[T>G]T");
    assert_eq!(SBS384_CHANNELS[96], "U:A[C>A]A");
    assert_eq!(SBS384_CHANNELS[191], "U:T[T>G]T");
    assert_eq!(SBS384_CHANNELS[192], "B:A[C>A]A");
    assert_eq!(SBS384_CHANNELS[287], "B:T[T>G]T");
    assert_eq!(SBS384_CHANNELS[288], "N:A[C>A]A");
    assert_eq!(SBS384_CHANNELS[383], "N:T[T>G]T");

    assert_eq!(SBS1536_CHANNELS[0], "AA[C>A]AA");
    assert_eq!(SBS1536_CHANNELS[1535], "TT[T>G]TT");

    assert_eq!(DBS78_CHANNELS[0], "AC>CA");
    assert_eq!(DBS78_CHANNELS[77], "TT>GG");
}

/// No empty and no duplicate labels in any table.
#[test]
fn labels_are_unique_and_non_empty() {
    fn check(labels: &[&str]) {
        assert!(labels.iter().all(|l| !l.is_empty()));
        let unique: HashSet<&str> = labels.iter().copied().collect();
        assert_eq!(unique.len(), labels.len());
    }
    check(&SBS96_CHANNELS);
    check(&SBS192_CHANNELS);
    check(&SBS384_CHANNELS);
    check(&SBS1536_CHANNELS);
    check(&DBS78_CHANNELS);
}
