#!/usr/bin/env Rscript
# gen-citation: regenerate inst/CITATION from DESCRIPTION (U-M7-04 slice-C, C1).
#
# Why generated: the CITATION file repeats Package/Title/Version/Authors, so
# a hand-kept copy rots the moment DESCRIPTION is bumped. This script is the
# single extraction site; the byte-exact sync guard lives in
# tests/testthat/test-release-materials.R (same "regenerate and compare"
# trust model as the roxygen baseline reproduction).
#
# Field policy:
#   * Package/Title/Version/Authors@R/URL are extracted from DESCRIPTION at
#     generation time -- no version literals are typed into this file or the
#     generated CITATION by hand.
#   * author = is carried BYTE-FAITHFUL from the Authors@R person() call
#     (shape validated, never recomposed).
#   * The benchmark note cites reproducibility anchors BY PATH only (driver
#     script + committed Seeds.txt); both existence-checked before writing.
#   * bibentry() carries the meta slots textVersion + note (R 4.5 utils
#     measurement: bibentry(bibtype, textVersion, header, footer, key, ...,
#     other, mheader, mfooter)); the historical citableAs() macro does not
#     exist in this toolchain's utils namespace and is therefore absent.
#
# Run:  Rscript tools/gen-citation.R [--out=<path>]   (default inst/CITATION)

options(warn = 1)

.repo_root <- local({
  a <- commandArgs(FALSE)
  f <- sub("^--file=", "", a[grep("^--file=", a)])
  if (length(f) > 0L) dirname(dirname(normalizePath(f[1]))) else normalizePath(".")
})

.args <- commandArgs(FALSE)
.out <- sub("^--out=", "", .args[grep("^--out=", .args)])
if (length(.out) == 0L) .out <- file.path(.repo_root, "inst", "CITATION")

.desc <- readLines(file.path(.repo_root, "DESCRIPTION"), warn = FALSE)

# Single-line field extractor: the key must appear exactly once and the
# value must not continue onto an indented continuation line.
.field <- function(key) {
  hit <- grep(paste0("^", key, ":"), .desc)
  if (length(hit) != 1L) {
    stop(sprintf("gen-citation: DESCRIPTION field '%s' must appear exactly once (found %d)",
                 key, length(hit)), call. = FALSE)
  }
  nxt <- hit + 1L
  if (!(nxt > length(.desc) || !grepl("^[[:space:]]+[^[:space:]]", .desc[nxt]))) {
    stop(sprintf("gen-citation: multi-line '%s' is not supported", key), call. = FALSE)
  }
  trimws(sub(paste0("^", key, ":[[:space:]]*"), "", .desc[hit[1]]))
}

pkg   <- .field("Package")
title <- .field("Title")
ver   <- .field("Version")
url   <- .field("URL")
auths <- .field("Authors@R")

# person() shape gate (byte-faithful carry-over, validation only).
mm <- gregexec(
  '^person\\("[^"]+",[[:space:]]*"[^"]+"[[:space:]]*,[[:space:]]*email[[:space:]]*=[[:space:]]*"[^"]+"[[:space:]]*,[[:space:]]*role[[:space:]]*=[[:space:]]*c\\([^)]*\\)[[:space:]]*\\)$',
  auths, perl = TRUE)[[1]]
if (anyNA(mm)) {
  stop("gen-citation: Authors@R must be one person(\"given\", \"family\", email = ..., role = c(...)) call",
       call. = FALSE)
}

# Reproducibility anchors: paths only, existence asserted at generation time.
.anchor.driver <- "bench/m7/tools/run_m7_bench.sh"
.anchor.seeds  <- "bench/results/docker_m7_degraded_20261009-184833/Seeds.txt"
if (!file.exists(file.path(.repo_root, .anchor.driver))) {
  stop(paste0("gen-citation: missing benchmark driver ", .anchor.driver), call. = FALSE)
}
if (!file.exists(file.path(.repo_root, .anchor.seeds))) {
  stop(paste0("gen-citation: missing committed seeds ", .anchor.seeds), call. = FALSE)
}

.year <- format(Sys.time(), "%Y")

lines <- c(
  "# Generated by tools/gen-citation.R from DESCRIPTION -- do not edit by hand.",
  "# After a Version (or Title/Authors/URL) change, regenerate:",
  "#   Rscript tools/gen-citation.R",
  "# The sync guard runs in tests/testthat/test-release-materials.R.",
  "",
  "bibentry(",
  '  bibtype = "Manual",',
  sprintf('  title = "%s: %s",', pkg, title),
  paste0("  author = ", auths, ","),
  sprintf('  year = "%s",', .year),
  sprintf('  textVersion = "%s",', ver),
  sprintf('  url = "%s",', url),
  sprintf('  note = "R package version %s"', ver),
  ")",
  "",
  "# Methods-availability note: the M7 measurement protocol is cited by",
  "# path -- the driver and the seed vectors are auditable committed files.",
  paste0('citFooter("For the M7 benchmark measurement protocol and reproducibility',
         ' anchors, run ', .anchor.driver,
         '; the committed seed vectors live in ', .anchor.seeds, '.")'),
  ""
)

if (!dir.exists(dirname(.out))) dir.create(dirname(.out), showWarnings = FALSE)
con <- file(.out, open = "wb")
writeLines(lines, con)
close(con)

cat(sprintf("gen-citation: wrote %s (%d lines, version %s, year %s)\n",
            .out, length(lines), ver, .year))
