# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib msuiter, .registration = TRUE
NULL

msffi_column_major_probe <- function(x) .Call(wrap__msffi_column_major_probe, x)

msffi_na_probe <- function(x) .Call(wrap__msffi_na_probe, x)

msffi_error_probe <- function(i, j) .Call(wrap__msffi_error_probe, i, j)

msffi_interrupt_probe <- function(n_chunks, n_threads) .Call(wrap__msffi_interrupt_probe, n_chunks, n_threads)

msffi_thread_probe <- function(n_items, seed, n_threads) .Call(wrap__msffi_thread_probe, n_items, seed, n_threads)

msffi_nmf_replicates_probe <- function(counts, k, replicates, max_iter, seed, n_threads) .Call(wrap__msffi_nmf_replicates_probe, counts, k, replicates, max_iter, seed, n_threads)

msffi_build_info <- function() .Call(wrap__msffi_build_info)

ms_tally_rust <- function(genome_path, chrom, pos, ref_, alt, sample, strand, want_sbs96, want_sbs192, want_sbs384, want_sbs1536, want_dbs78, want_id83, n_threads) .Call(wrap__ms_tally_rust, genome_path, chrom, pos, ref_, alt, sample, strand, want_sbs96, want_sbs192, want_sbs384, want_sbs1536, want_dbs78, want_id83, n_threads)

ms_extract_rust <- function(counts, k, max_iter, seed, engine, n_threads) .Call(wrap__ms_extract_rust, counts, k, max_iter, seed, engine, n_threads)

ms_pipeline_rust <- function(counts, k, replicates, max_iter, seed, k_folds, n_seeds, n_threads) .Call(wrap__ms_pipeline_rust, counts, k, replicates, max_iter, seed, k_folds, n_seeds, n_threads)

ms_stratify_rust <- function(counts, manual_cutoff, seed, n_threads) .Call(wrap__ms_stratify_rust, counts, manual_cutoff, seed, n_threads)

ms_ard_rust <- function(counts, k0, max_iter, tol, a0, b0, seed, n_threads) .Call(wrap__ms_ard_rust, counts, k0, max_iter, tol, a0, b0, seed, n_threads)

ms_sparse_rust <- function(counts, k, max_iter, variant, lambda, mu, delta, tol, seed, n_threads) .Call(wrap__ms_sparse_rust, counts, k, max_iter, variant, lambda, mu, delta, tol, seed, n_threads)

ms_fit_rust <- function(counts, signatures, method, nb_size, tol, max_iter, zero_threshold, n_threads) .Call(wrap__ms_fit_rust, counts, signatures, method, nb_size, tol, max_iter, zero_threshold, n_threads)

ms_fit_bootstrap_rust <- function(counts, signatures, method, n_boot, nb_size, zero_threshold, seed, n_threads) .Call(wrap__ms_fit_bootstrap_rust, counts, signatures, method, n_boot, nb_size, zero_threshold, seed, n_threads)

ms_test_presence_rust <- function(counts, signatures, nb_size, n_threads) .Call(wrap__ms_test_presence_rust, counts, signatures, nb_size, n_threads)

ms_match_solutions_rust <- function(estimated, reference, dim, thresholds) .Call(wrap__ms_match_solutions_rust, estimated, reference, dim, thresholds)

# nolint end
