# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib msuiter, .registration = TRUE
NULL

msffi_column_major_probe <- function(x) .Call(wrap__msffi_column_major_probe, x)

msffi_na_probe <- function(x) .Call(wrap__msffi_na_probe, x)

msffi_error_probe <- function(i, j) .Call(wrap__msffi_error_probe, i, j)

msffi_interrupt_probe <- function(n_chunks, n_threads) .Call(wrap__msffi_interrupt_probe, n_chunks, n_threads)

msffi_thread_probe <- function(n_items, seed, n_threads) .Call(wrap__msffi_thread_probe, n_items, seed, n_threads)

msffi_nmf_replicates_probe <- function(counts, k, replicates, max_iter, seed, n_threads) .Call(wrap__msffi_nmf_replicates_probe, counts, k, replicates, max_iter, seed, n_threads)

msffi_build_info <- function() .Call(wrap__msffi_build_info)

ms_tally_rust <- function(genome_path, chrom, pos, ref_, alt, sample, strand, want_sbs96, want_sbs192, want_sbs384, want_sbs1536, want_dbs78, n_threads) .Call(wrap__ms_tally_rust, genome_path, chrom, pos, ref_, alt, sample, strand, want_sbs96, want_sbs192, want_sbs384, want_sbs1536, want_dbs78, n_threads)

ms_extract_rust <- function(counts, k, max_iter, seed, engine, n_threads) .Call(wrap__ms_extract_rust, counts, k, max_iter, seed, engine, n_threads)

ms_stratify_rust <- function(counts, manual_cutoff, seed, n_threads) .Call(wrap__ms_stratify_rust, counts, manual_cutoff, seed, n_threads)

# nolint end
